server:
  port: 8080
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8
spring:
  #--------------------------charset--------------------------
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

  mvc:
    static-path-pattern: /**
  thymeleaf:
    #模板的模式，支持 HTML, XML TEXT JAVASCRIPT
    mode: HTML
    #编码 可不用配置
    encoding: UTF-8
    #内容类别,可不用配置
    servlet:
      content-type: text/html
    #开发配置为false,避免修改模板还要重启服务器
    cache: false
    #配置模板路径，默认是templates，可以不用配置
    prefix: classpath:/templates/
    suffix: .html
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/supermarket?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root123
  quartz:
    job-store-type: jdbc
mybatis:
  config-location: classpath:mapper/config/mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml

### 调度中心部署跟地址 [选填]：如调度中心集群部署存在多个地址则用逗号分隔。执行器将会使用该地址进行"执行器心跳注册"和"任务结果回调"；为空则关闭自动注册；
xxl:
  job:
    admin:
      # 这边表示连接带调度中心的地址
      addresses: http://127.0.0.1:8082/xxl-job-admin
    # 实例执行器的相关配置
    executor:
      # 执行器名称
      appname: xxl-job-executor-sample
      #ip设置
      ip:
      # 注册的端口
      port: 9999
      # 日志地址
      logpath: /data/applogs/xxl-job/jobhandler
      ### xxl-job log retention days
      logretentiondays: -1
    # 如过要加密的话 对称
    accessToken:
